import numpy as np, pandas as pd, itertools, gc, warnings; warnings.filterwarnings("ignore")
D="/sessions/dazzling-sweet-pascal/mnt/outputs/deliverables/aptamer-switch-bias/data/atp_corrected.csv.gz"
d=pd.read_csv(D); d=d[d.seq.str.len()==10]
print(f"rows after length filter: {len(d):,}   (README: 494,065 clusters)")
g=d.groupby("seq")["ratio"].agg(["mean","size"]); del d; gc.collect()
s=g.index.to_numpy(); N=len(s)
print(f"unique 10-mers: {N:,}   (README: 339,373)   MATCH={N==339373}")
rng=np.random.default_rng(0); perm=rng.permutation(N)
hold=perm[:60000]; pool=perm[60000:]; val=pool[:40000]; train=pool[40000:]
Eh=np.load("/tmp/E_hold.npy"); Ev=np.load("/tmp/E_val.npy"); Rh=np.load("/tmp/R_hold.npy")
print()
print("CHECK 1 - do the independently-computed splits agree?")
print(f"  ENS1 hold == freshly recomputed hold : {np.array_equal(Eh,hold)}")
print(f"  R2TEST hold == freshly recomputed    : {np.array_equal(Rh,hold)}")
print(f"  ENS1 val  == freshly recomputed val  : {np.array_equal(Ev,val)}")
print(f"  -> R_pgbm.npy predictions therefore align with E_hold: {np.array_equal(Rh,Eh)}")
print()
print("CHECK 2 - sanity on saved arrays")
gh=np.load("/tmp/R_pgbm.npy"); gv=np.load("/tmp/E_gv.npy"); y=np.load("/tmp/E_y.npy")
print(f"  R_pgbm (hold preds) len {len(gh):,}  expect 60,000  ok={len(gh)==60000}")
print(f"  E_gv   (val preds)  len {len(gv):,}  expect 40,000  ok={len(gv)==40000}")
print(f"  E_y    (all y)      len {len(y):,}  expect {N:,}  ok={len(y)==N}")
yfresh=g["mean"].to_numpy().astype(np.float32)
print(f"  saved y identical to freshly computed y: {np.allclose(y,yfresh)}")
print()
print("CHECK 3 - no train/hold leakage")
print(f"  hold ∩ pool empty: {len(set(hold.tolist())&set(pool.tolist()))==0}")
print(f"  val  ∩ train empty: {len(set(val.tolist())&set(train.tolist()))==0}")
print(f"  hold ∩ val empty:  {len(set(hold.tolist())&set(val.tolist()))==0}")
print()
print("CHECK 4 - is the GBM hold R2 reproducible from saved preds?")
r2=1-((y[hold]-gh)**2).sum()/((y[hold]-y[hold].mean())**2).sum()
print(f"  recomputed GBM hold R2 from saved preds = {r2:.4f}  (reported 0.4940)")
